name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [21]
        ndk: [21.4.7075529]
        abi: [x86_64]
        configuration: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install package
        run: |
          brew install ninja

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.abi }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: ${{ matrix.abi }}
          profile: Nexus 6
          api-level: ${{ matrix.api-level }}
          ndk: ${{ matrix.ndk }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Grant execution authority
        working-directory: ./app/src/scripts
        run: |
          chmod +x ./test_runner.sh

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon assembleAppTest${{ matrix.configuration }}

      - name: Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: ${{ matrix.abi }}
          profile: Nexus 6
          api-level: ${{ matrix.api-level }}
          ndk: ${{ matrix.ndk }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: |
            cd ${{ github.workspace }}/app/src/scripts && chmod +x ./ctest.sh && ./ctest.sh ${{ matrix.abi }} -j 4 -C ${{ matrix.configuration }}
